export const REGISTER_SUCCESS: string = "REGISTER_SUCCESS";
export const REGISTER_FAIL: string = "REGISTER_FAIL";
export const LOGIN_SUCCESS: string = "LOGIN_SUCCESS";
export const LOGIN_FAIL: string = "LOGIN_FAIL";
export const LOGOUT: string = "LOGOUT";

export const SET_MESSAGE: string = "SET_MESSAGE";
export const CLEAR_MESSAGE: string = "CLEAR_MESSAGE";

export const FETCH_SCRAPE_REQUEST_SUCCESS: string = "FETCH_SCRAPE_REQUEST_SUCCESS";
export const FETCH_SCRAPE_REQUEST_FAILED: string = "FETCH_SCRAPE_REQUEST_FAILED";

export const FETCH_TRENDS_SUCCESS: string = "FETCH_TRENDS_SUCCESS";
export const FETCH_TRENDS_FAILED: string = "FETCH_TRENDS_FAILED";

export const FETCH_TWEETS_SUCCESS: string = "FETCH_TWEETS_SUCCESS";
export const FETCH_TWEETS_FAILED: string = "FETCH_TWEETS_FAILED";
export const FETCH_TWEETS_CHART_SENTIMENT_SUCCESS: string = "FETCH_TWEETS_CHART_SENTIMENT_SUCCESS";
export const FETCH_TWEETS_CHART_SENTIMENT_FAILED: string = "FETCH_TWEETS_CHART_SENTIMENT_FAILED";
export const FETCH_TWEETS_CHART_TRENDS_SUCCESS: string = "FETCH_TWEETS_CHART_TRENDS_SUCCESS";
export const FETCH_TWEETS_CHART_TRENDS_FAILED: string = "FETCH_TWEETS_CHART_TRENDS_FAILED";
